### ISSUE TITLE
Разделить по разным папкам исходники скачанных библиотек, собранные библиотеки для разных платформ и архитектур, и папку сборки проекта

### ISSUE THREAD

**Issue by NikitaFeodonit** [nextgis-borsch/borsch#1]
Сейчас при сборке для каждой платформы нужные библиотеки вытягиваются заново и кладутся в папку build-<arch>. В итоге получается, что одно и то же вытягивается за сборку несколько раз, в зависимости от количества платформ. И если нужно очистить сборку, что обычно проще всего сделать удалением папки build, то множественное скачивание будет заново.

Думаю, было бы хорошо разделить по разным папкам
- исходники библиотек,
- собранные и проинсталированные библиотеки,
- сборку текущего проекта.

То есть можно сделать, например, так.

Папка для скачанных библиотек с разделением по их версиям

```
build-lib-sources/<lib-name>/<version>
```

или

```
build-lib-sources/<lib-name>-<version>
```

как удобнее.

Папка для собранных библиотек с разделением по платформам (Lin, Win, Android ...), архитектурам (x86, arm ...), версиям библиотек

```
build-libs/<platform>/<arch>/<lib-name>/<version>
```

или аналогично вместо вложенных папок длинное имя папки, как удобнее.

Папка для сборки нашей библиотеки, где также разделение по платформам и архитектурам и, возможно, по версиям.

```
build/<platform>/<arch>
```

А при сборке проверять (может сам cmake проверит) что скачано и собрано, то и использовать. Тогда очистить папку сборки текущего проекта будет проще, без скачивания и пересборки всех библиотек.

Также сделать разные уровни очистки сборки для этих папок:
clean (только для папки build)
clean-all (+ папка build-libs)
clean-all-with-lib-sources (+ папка build-lib-sources)

**Comment by BishopGIS** [comment]
@NikitaFeodonit вроде сделано - почему тикет не закрыт?

**Comment by NikitaFeodonit** [comment]
Закрыл.
