### ISSUE TITLE
Does FindExtProject need get_binary_package defaults for ${repo} and ${repo_type} 

### ISSUE THREAD

**Issue by dakotahawkins** [nextgis-borsch/borsch#10]
I'm trying to test a borsch build of gdal and running into some issues, please forgive me if I missed something obvious.

I see an early cmake configuration error:

```
CMake Error at build/_deps/borsch-src/cmake/FindExtProject.cmake:99 (get_binary_package):
  get_binary_package Function invoked with incorrect arguments for function
  named: get_binary_package
Call Stack (most recent call first):
  build/_deps/borsch-src/cmake/FindAnyProject.cmake:72 (find_extproject)
  CMakeLists.txt:12 (find_anyproject)
```

Trying to include GDAL like this:

```CMake
include(FindAnyProject)

set(WITH_GDAL ON CACHE BOOL "GDAL on" FORCE)
set(WITH_GDAL_EXTERNAL ON CACHE BOOL "GDAL external on" FORCE)
find_anyproject(GDAL REQUIRED DEFAULT ON SHARED OFF)
```

How are `${repo}` and `${repo_type}` supposed to be set for this call?

https://github.com/nextgis-borsch/borsch/blob/deba6551f355046aa5e9f442f77911bf48a892e7/cmake/FindExtProject.cmake#L98

**Comment by BishopGIS** [comment]
The ``${repo}`` and ``${repo_type}`` set in ``FindExt<your package name>.cmake``. 
For example you can see: https://github.com/nextgis-borsch/borsch/blob/master/cmake/FindExtEXPAT.cmake

For variable ``${repo_type}`` only ``github`` value is supported now. 

I just updated FindExtXXX.cmake files  (https://github.com/nextgis-borsch/borsch/tree/master/cmake) for Borsch v2 and using instructions here: https://github.com/nextgis-borsch/borsch#common-cmake-scripts

**Comment by dakotahawkins** [comment]
@BishopGIS Thanks! I think I didn't realize that some of the Borch-based libraries were slightly ahead of the main repo. I saw that the `FindExt*.cmake` files were setting `${repo_name}` but didn't realize that they needed to be updated.
