### ISSUE TITLE
FindExtProject calls get_compiler_version function not present in util.cmake

### ISSUE THREAD

**Issue by dakotahawkins** [nextgis-borsch/borsch#11]
Context: https://github.com/nextgis-borsch/borsch/blob/11d3752185983da375ad893a365139bb682c1a97/cmake/FindExtProject.cmake#L35

`get_compiler_version` isn't included in this version of `cmake/util.cmake` but is present in the version used by [postgis](https://github.com/nextgis-borsch/postgis/blob/76844884c2073b8edf07d02e4920e420ffb8a661/cmake/util.cmake#L196).

**Comment by BishopGIS** [comment]
Fixed in 733cd9680aba7deb9901d84d2cc4e0e333f3245f
