### ISSUE TITLE
gdal-bin from ppa should be 2.4 but is 2.2

### ISSUE THREAD

**Issue by swiss-knight** [nextgis-borsch/borsch#12]
I followed the commands here for Ubuntu 18.04 64 bits:     
http://nextgis.com/borsch    

It should have installed gdal-bin 2.4.0 for bionic as stated here:    
https://launchpad.net/~nextgis/+archive/ubuntu/ppa?field.series_filter=bionic     

Now `gdalinfo` gives me this:
```
$ gdalinfo --version
GDAL 2.2.3, released 2017/11/20
```

and `gdal_translate` is complaining:
```
$ gdal_translate --version
ERROR 1: gdal_translate was compiled against GDAL 2.4, but the current library version is 2.2
```
Here's the apt source file content:    
```
$ cat /etc/apt/sources.list.d/nextgis-ubuntu-ppa-bionic.list
deb http://ppa.launchpad.net/nextgis/ppa/ubuntu bionic main
# deb-src http://ppa.launchpad.net/nextgis/ppa/ubuntu bionic main
# deb-src http://ppa.launchpad.net/nextgis/ppa/ubuntu bionic main

```

And the bonus question; is it planned to integrate proj 6?  :+1:    
https://trac.osgeo.org/gdal/wiki/rfc73_proj6_wkt2_srsbarn 
  
Thanks.

**Comment by BishopGIS** [comment]
Just tested on fresh Ubuntu 18.04 LTS install:

> $ gdalinfo --version
> GDAL 2.4.0, released 2018/12/14
> $ gdal_translate --version
> GDAL 2.4.0, released 2018/12/14
> $ lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 18.04 LTS
> Release:          18.04
> Codename:     bionic

Not reproduced. 

It seems to me you have some problems with previous install **GDAL 2.2.3**. Try to completely remove it: 

> apt purge gdal-bin python-gdal
> apt autoremove

**Note**: This GDAL build based on borsch building system and has differences from original GDAL package. Details is here: https://github.com/nextgis-borsch/lib_gdal/blob/master/README.md. Some packages from Ubuntu repository may conflicts with our GDAL package. 

About Proj 6 - it's in our plans. But we will wait GDAL 2.5 release with full Proj6 support.
